server:
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: postgres
    source: "postgres://postgres:ghq92DAU712.9dn@localhost:5432/customerdb?sslmode=disable"

  redis:
    network: tcp
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
